<%@ Page Language="C#" MasterPageFile="~/Views/Shared/Blank.Master" Inherits="System.Web.Mvc.ViewPage<Monnit.Customer>" %>

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
    Login
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <div class="login_container">

        <div class="login_form_container">

            <div class="login_logo_container text-center">
                <%if (MonnitSession.CurrentBinaryStyle("Logo") != null && MonnitSession.CurrentBinaryStyle("Logo").Length > 0){%>
                <img class="siteLogo" src="/Overview/Logo" />
                <%}else{%>
                <img class="siteLogo" src="<%= Html.GetThemedContent("/images/Logo_TopBar.png")%>" />
                <%} %>
                <div id="siteLogo2"></div>
            </div>

            <!-- 2FA Setup (no smtp && no customerTotp) -->
            <div  class="TOTPSetup login-form-container login_form">
                <form class="enabled" style="margin-left: 20px;">

                    <div class="step">
                        <div>
                            <p>1</p>
                        </div>
                        <h3>Scan the barcode</h3>
                    </div>

                    <p>Scan the barcode below with your authenticator app or type in the code:</p>

                    <div id="qrCode"></div>

                    <p class="totpCode"><%=ViewBag.secretCode%></p>

                    <div class="step step2">
                        <div>
                            <p>2</p>
                        </div>
                        <h3>Enter the verification code</h3>
                    </div>

                    <p>Once you have scanned the barcode or entered the above code, enter the 6-digit verification code generated by the authenticator application.</p>

                    <div>
                        <input class="form-control" name="Code" placeholder="verification code" id="code" required="required" type="number" />
                    </div>

                    <div class="form-group has-error">
                        <p id="totpCodeError"></p>
                    </div>

                </form>
                <div style="margin-left: 20px;" class="form-group center enabled">
                    <button class="btn btn-primary" style="width:306px;" id="totpSubmit">
                        Verify Code
                    </button>
                </div>

                <p style="margin-left: 20px;" class="enabled"><strong>This device will be remembered for 90 days.</strong></p>
            </div>

        </div>

        <div class="login_image">
            <img src="<%= Html.GetThemedContent("/images/login-dashPhone.png")%>" style="width: 100%;" />
        </div>

    </div>

    <script type="text/javascript" src="../../Scripts/QRCode_Generator/qrcode.js"></script>
    <script type="text/javascript">

        $("#totpSubmit").click(function (e) {
            e.preventDefault();
            $.ajax({
                url: '/Settings/VerifyTotp',
                type: 'post',
                data: { code: $('#code').val() },
                success: function (e) {
                    if (e == 'Success') {
                        window.location.href = 'FinalizeLogin?returnUrl=<%=ViewBag.returnUrl%>'
                    }
                    else {
                        $('#totpCodeError').html(e);
                    }
                }
            })
        })

        new QRCode(document.getElementById('qrCode'),
            {
                text: "<%=ViewBag.qr%>",
                width: 120,
                height: 120
            });

    </script>

    <style>

        h2 {
            font-size: 30px;
        }

        .login_logo_container {
            padding-bottom: 20px;
        }

        input::-webkit-outer-spin-button,
        input::-webkit-inner-spin-button {
            -webkit-appearance: none;
            margin: 0;
        }

        input[type=number] {
            -moz-appearance:textfield;
        }

        form {
            width: 350px;
        }

        .step div {
            background: #0067ab;
            border-radius: 25px;
            color: white;
            width: 25px;
            height: 25px;
            display:flex;
            justify-content: center;
            align-items: center;
        }

        .step {
            margin-top:20px;
            display: flex;
            align-items: center;
        }

        .step p {
            margin: auto;
        }

        .step h3 {
            margin-left: 5px;
        }

        .TOTPForm p {
            margin: 10px 0;
        }

        .totpCode {
            padding: 5px;
            background: #ddd;
            text-align:center;
            margin: 10px 0;
            width: 100%;
        }

        #TFA_QR {
            width:140px;
            margin: 5px 0;
        }

        .center {
            text-align: center;
        }

    </style>

</asp:Content>