<%@ Control Language="C#" Inherits="System.Web.Mvc.ViewUserControl<dynamic>" %>

    <div class="col-md-12 col-sm-12 col-xs-12">
        <p>The terms and conditions below (the "Terms") together with the Privacy Policy, Cookie Policy, and Data Policies govern your access to and use of the Sensor Cert web site and related mobile applications, products, and services (collectively, the "Site"), excluding any products and services provided to you by us under a separate written agreement. The Site is offered and provided by Sensor Cert LLC ("we", "us", or "our"). In some instances, using our Site requires that you install our software on your computer or mobile device (the "Software"). By accessing our Site and in order to install or use Software, you must agree to these Terms without modification by you. You may terminate these Terms at any time by uninstalling the Software (if any), canceling your account with us, and no longer accessing our Site. Some provisions will continue to be effective after termination of these Terms. These Terms constitute a legal agreement between you and us. You agree to these Terms by accessing or using the Site or our Software. Do not access or use the Site or our Software if you are unwilling or unable to be bound by these Terms.</p>
        <h2>1.  Definitions.</h2>
        <p>a. A "user" is someone who accesses, browses, crawls, scrapes, or in any way uses the Site. The terms "you" and "your" refer to you, as a user of the Site.</p>
        <p>b. "Content" means text, images, photos, audio, video, and all other forms of data or communication whether on www.sensorcert.com or any other Sensor Cert website. "Your Content" means Content that you submit or transmit to or through the Site, such as location and/or other account or sensor information and any message you may post on or through the Site or information that you display as part of your account profile. "User Content" means Content that users submit or transmit to or through the Site including Your Content. "Our Content" means Content that we create and make available on the Site. "Third Party Content" means Content that is made available on the Site by parties other than us or our users, such as data providers who license data to us for use on the Site. "Site Content" means all of the Content that is made available on the Site, including Your Content, User Content, Third Party Content, and Our Content.</p>
        <p>c. Software means any software provided whether downloaded, viewed or embedded.</p>
        <p>d. Hardware means any device, gateway or sensor.</p>
        <h2>2.  Eligibility.</h2>
        <p>The Site and the Software are not intended for children under the age of 13 and we do not knowingly collect information from children under the age of 13.  If we become aware that an individual is under the age of 13 and has submitted any information to us for any purpose, we will delete his or her information from our files.   In addition, if a parent or guardian becomes aware that a child has submitted personal information, that parent or guardian should immediately tell us that they would like this information deleted from our records by contacting us at the email address listed on the Site. If you are 13 or older but under the age of 18, you should review these terms and conditions with your parent or guardian to make sure that you and your parent or guardian understand these terms and conditions. Further, you represent and warrant that you (a) have not previously been suspended by us or removed from the Site; (b) do not have more than one account for the Site at any given time; and (c) that you have full power and authority to enter into these Terms and in doing so will not violate any other agreement to which you are a party.</p>
        <h2>3. Privacy/Cookie/Data.</h2>
        <p>We encourage you to review our privacy policy which can be found at <a href="http://www.sensorcert.com/privacy.html" target="_blank">http://www.sensorcert.com/privacy.html</a> ("Privacy Policy"). Also our <a href="/account/cookie" target="_blank">Cookie Policy</a>. And our <a href="/account/data" target="_blank">Data Policies</a>. By agreeing to these Terms you are also agreeing to our Privacy Policy, Cookie, and Data Policies. These policies govern the collection, use and disclosure of information we collect from you. The information we collect is stored and processed by us on servers in the United States and potentially other countries. By installing the Software or using the Site you consent to any such transfer of your information outside your country and/or outside the country where you access or use the Site or have installed the Software.</p>
        <h2>4. Changes to the Terms.</h2>
        <p>We may modify these Terms from time to time. When changes are made, we will notify you by making the revised version available on this webpage and changing the Effective Date at the end of these terms. You should revisit these Terms on a regular basis as revised versions will be binding on you. Any such modification will be effective upon our posting of new Terms. You understand and agree that your continued access to or use of the Site or Software after any posted modification to the Terms indicates your acceptance of the modification.</p>
        <h2>5. User Accounts.</h2>
        <p>You need to create an account and provide information about yourself in order to use some of the features on the Site. You are responsible for maintaining the confidentiality of your account password. You are also responsible for all activities that occur in connection with your account. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to close your account at any time for any or no reason. If you are an end-user, you will use your account for your personal, non-commercial use only. In creating an Account, you may not impersonate someone else, create an account for anyone other than yourself or  company which you are able to legally bind to these terms, provide an email  address other than your own unless you have explicit permission from the email  owner, or create multiple accounts. Some features of the Site may allow you to send and receive text messages (SMS) to your or others’ mobile devices. The number of messages per month will depend upon your settings.  You grant us authorization to send SMS to your account. Message and data rates may apply and you will be responsible for paying such charges. Check with your carrier if you have questions about your plan and costs. To stop receiving text messages from this service, terminate the notifications within your account.</p>
        <p>You authorize us and our affiliates, agents and independent contractors to contact you at any telephone number you provide to us or from which you place a call to us, or any telephone number where we believe we may reach you using any means of communication, including, but not limited to, calls or text messages to mobile, cellular, wireless or similar devices and calls or text messages using an automated telephone dialing system and/or artificial voices or prerecorded messages, even if you incur charges for receiving such communications. You also agree that we and our affiliates, agents and independent contractors may use any other medium, as permitted by law and including, but not limited to, mail, text message and e-mail, to contact you.  If you want to make a change in how we contact you, including with respect to any telephone number that we might use, please contact us.  You agree that we and our affiliates, agents and independent contractors may listen to or record telephone calls between you and our representatives without additional notice to you.</p>
        <h2>6. Use of the Site.</h2>
        <p>We grant you permission to use the Site subject to the restrictions in these Terms. In accessing or using the Site, you may be exposed to Content that is offensive, indecent, inaccurate, objectionable, or otherwise inappropriate. We do not endorse or condone such Content. You therefore access and use the Site at your own risk. We reserve the right to set limits on the use of the Site at our discretion.  WE DO NOT GUARANTEE THAT ANY DATA TRANSMITTED TO OR FROM OUR SITE WILL BE ACCURATE OR WITHOUT MISTAKES. YOU ACKNOWLEDGE THAT USING THE SENSOR CERT PRODUCTS IN A MANNER OTHER THAN SPECIFIED IN THE USER MANUAL MAY CAUSE INJURY OR HARM TO PERSON(S) OR PROPERTY.</p>
        <h2>7. Restrictions on Use.</h2>
        <p>You agree that you will not, and will not assist or enable others to:</p>
        <p>a. use the Site or Site Content to threaten, stalk, defraud, incite, harass, or advocate the harassment of another person, or otherwise interfere with another user's use of the Site;</p>
        <p>b. use the Site for promotional or commercial purposes, except as expressly allowed in writing by us;</p>
        <p>c.  use the Site to violate any third-party right, including any breach of confidence, copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right;</p>
        <p>d. use the Site in violation of these Terms or any applicable law;</p>
        <p>e. modify, adapt, appropriate, reproduce, distribute, translate, create derivative works or adaptations of, publicly display, sell, trade, or in any way exploit the Site or Site Content (other than Your Content), except as expressly authorized by us;</p>
        <p>f. reverse engineer any portion of the Software, Hardware or  Site;</p>
        <p>g. remove or modify any copyright, trademark or other proprietary rights notice on the Site or on any materials printed or copied off of the Site</p>
        <p>h. record, process, or mine information about other users;</p>
        <p>i. use any robot, spider, site search/retrieval application, or other automated device, process or means to access, retrieve, scrape, or index the Site or any Site Content;</p>
        <p>j. access, retrieve or index the Site for purposes of constructing or populating a searchable database;</p>
        <p>k. reformat or frame any portion of the Site;</p>
        <p>l. take any action that imposes, or may impose in our sole discretion, an unreasonable or disproportionately large load on our technology infrastructure;</p>
        <p>m. attempt to gain unauthorized access to the Site, user accounts, computer systems or networks connected to the Site through hacking, password mining or any other means; use the Site or any Site Content to transmit any computer viruses, worms, defects, Trojan horses or other items of a destructive nature (collectively, "Viruses"); use any device, software or routine that interferes with the proper working of the Site, or otherwise attempt to interfere with the proper working of the Site; make excessive traffic demands; use the Site to violate the security of any computer network, crack passwords or security encryption codes; disrupt or interfere with the security of, or otherwise cause harm to, the Site or Site Content; remove, circumvent, disable, damage or otherwise interfere with any security-related features of the Site, features that prevent or restrict the use or copying of Site Content, or features that enforce limitations on the use of the Site.</p>
        <h2>8. Permission to Use Your Content.</h2>
        <p>At our sole discretion, we may display Your Content on the Site in order to provide our service(s) and we may use Your Content to promote our Site, Software, and our services and for other business uses. As such, you hereby grant us permission to use Your Content for our business purposes.  Please note, we reserve certain rights to preserve Your Content in our off-line servers as explained in our Data Policies. Finally, you irrevocably waive, and cause to be waived, any claims and assertions of moral rights or attribution with respect to Your Content.</p>
        <h2>9. Responsibility for Your Content.</h2>
        <p>You alone are responsible for Your Content. You assume all risks associated with Your Content, including anyone's reliance on its accuracy, completeness or usefulness. You represent that you own, or have the necessary permissions to use, and authorize the use of, Your Content as described herein. You may not imply that Your Content is in any way sponsored or endorsed by us.</p>
        <p>You may expose yourself to liability if, for example, Your Content violates any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; contains material that is false, intentionally misleading, or defamatory; contains material that is unlawful, including illegal hate speech or pornography; exploits or otherwise harms minors; or violates or advocates the violation of any law or regulation. </p>
        <h2>10. Use of Content.</h2>
        <p>We may remove or reinstate User Content from time to time at our sole discretion. We have no obligation to retain Your Content beyond any time period that may be specified in the plan you have subscribed to, nor do we guarantee any confidentiality or other responsibility with respect to Your Content.</p>
        <h2>11. Software License and Restrictions.</h2>
        <p>When you use this Site or create an account to use the Site, we grant you a personal, limited, non-transferable, non-sub-licensable, non-exclusive copyright license, solely for your own personal, non-commercial purposes, to view online or install the Software on one computer or mobile device and/or use the Software as it is delivered to you for the sole purpose of using the Site. These are your only rights with regard to the Software. You may not or assist or enable others to decode, reverse-translate, modify, reverse-engineer, decompile, disassemble, or otherwise reduce the Software into source code form. All communications between us and the Software and the content stored on our computer servers and in the Software includes our confidential information and you may not access, publish, transmit, display, create derivative works of, store, or otherwise exploit any such confidential information except as such functions are performed by the Software in the ordinary course of operation. You do not have the right to create derivative works of the Software. Nothing in these Terms shall be deemed to grant any right or license to You (by implication, estoppel, or otherwise), except as expressly provided herein and no other license, authority to infringe, or immunity from infringement liability shall be deemed to arise or exist as a matter of law or otherwise. The foregoing limitations shall in no way be deemed a derogation of the express rights granted under these Terms. Please see "Additional Notices" available at <a href="http://www.sensorcert.com/terms.html" target="_blank">http://www.sensorcert.com/terms.html</a> for ownership and licensing information about additional software components included with the Software, if any.</p>
        <h2>12. Patent Policy Statement.</h2>
        <p>We may own patent rights or other intellectual property rights for the inventions or other features embodied in the Software or Site. By using the Site or Software, or agreeing to these Terms, we are not granting you any right, title, interest, or license in or to any of our patents or patents of our affiliates including but not limited to those related to (a) system or sensor devices or gateway devices, or virtual models thereof, or (b) any proprietary software that may be used or distributed by us (in a download, install, online or embedded) or our affiliates or their respective customers, on system or sensor devices or gateway devices.</p>
        <h2>13. Third Party Software, Services and/or Products.</h2>
        <p>Included as part of the Site and/or the Software provided to you, there may be other software that is licensed and available to you which is subject to third party license agreements. To the extent that these Terms may conflict with licenses or agreements governing your rights to that software, the agreement or license applicable to such third party software is covered by the terms of its applicable license or agreement.</p>
        <p>We may make available third party products and services for purchase through the Site. Descriptions and images of, and references to, third party products or services available in connection with the Site do not imply our endorsement of such third party products or services. All descriptions, images, references, features, content, specifications, products and prices of products and services described or depicted on the Site are subject to change at any time without notice. Certain weights, measures and similar descriptions are approximate and are provided for convenience purposes only. The inclusion of any products or services on the Site at a particular time does not imply or warrant that these products or services will be available at any time. It is your responsibility to ascertain and obey all applicable local, state, federal and international laws (including minimum age requirements) in regard to the possession, use and sale of any item purchased from this Site. By placing an order, you represent that the products ordered will be used only in a lawful manner. We reserve the right, with or without prior notice, to limit the available quantity of or discontinue any product or service, to impose conditions on the honoring of, any coupon, coupon code, promotional code or other similar promotions, to bar you from making purchase(s), and/or to refuse to provide you with any product or service. You agree to pay all charges that may be incurred by you or on your behalf through the Site, at the price(s) in effect when such charges are incurred, including without limitation all shipping and handling charges. In addition, you remain responsible for any taxes that may be applicable to your purchases. The risk of loss and title to products purchased on the Site pass to the purchaser upon delivery to the carrier.</p>
        <h2>14. Intentionally Omitted.</h2>
        <h2>15. Notices of Copyright Infringement.</h2>
        <p>Notifications of claimed copyright infringement should be sent to Sensor Cert LLC's Designated Agent in writing at the following address:</p>
        <p>
            Sensor Cert LLC<br />
            Attn. Legal Department<br />
            9909 West Fairview Ave.<br />
            Littleton, CO 80127
        </p>
        <p>To be effective, the Notification must include the following:</p>
        <p>a. A physical or electronic signature of the owner whose exclusive right is allegedly infringed or a person authorized to act on his or her behalf;</p>
        <p>b. Identification of the copyrighted work claimed to have been infringed, or if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</p>
        <p>c. Identification of the material that is claimed to be infringing or is the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit us to locate the material on the Site;</p>
        <p>d. Information reasonably sufficient to permit us to contact the copyright owner or his/her authorized agent including an address, telephone number, and if available, an electronic mail address;</p>
        <p>e. A statement that the copyright owner or authorized agent has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law;</p>
        <p>f. A statement that the information in the notification is accurate, and if submitted by the owner's authorized agent a statement under penalty of perjury, that the agent is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
        <p>Within a commercially reasonable time after receipt of the written Notification containing the information as outlined in a through f above we will attempt to investigate the matter and if in our sole discretion, it is deemed meritorious, remove or disable access to the material that is alleged to be infringing and forward the written notification to the alleged infringer and take reasonable steps to promptly notify the alleged infringer that we have removed or disabled access to the allegedly infringing material.</p>
        <h2>16. Counter Notification:</h2>
        <p>To be effective, a Counter Notification must be a written communication provided to our Designated Agent at the above provided address that includes substantially the following:</p>
        <p>a. A physical or electronic signature of the alleged infringer;</p>
        <p>b. Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</p>
        <p>c. A statement under penalty of perjury that the alleged infringer has a good faith belief that the material was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled;</p>
        <p>d. The alleged infringer's name, address, and telephone number, and a statement that the alleged infringer consents to the jurisdiction of Federal District Court for Salt Lake County, Utah, or if the Subscriber's address is outside of the United States, for any judicial district in which we may be found, and that the alleged infringer will accept service of process from the person who provided notification or an agent of such person.</p>
        <p>After receipt of a Counter Notification containing the information as outlined in a through d above, we will attempt to investigate the matter and if in our sole discretion, it is deemed meritorious, provide the Complaining Party with a copy of the Counter Notification within a commercially reasonable time and inform the copyright owner or designated agent that we will replace the removed material or cease disabling access to it within ten (10) business days. If our designated agent has not received notice from the copyright owner or his/her designated agent within ten (10) business days that an action has been filed seeking a court order to restrain the alleged infringer from engaging in infringing activity in relation to the allegedly infringing material, we will restore the allegedly infringing material.</p>
        <h2>17. Site Availability.</h2>
        <p>We reserve the right to modify, update, or discontinue the Site at our sole discretion, at any time, for any or no reason, and without notice or liability.</p>
        <h2>18. Unauthorized Access.</h2>
        <p>We reserve the right to exercise whatever lawful means we deem necessary to prevent unauthorized access to or use of the Site, including, but not limited to, technological barriers, IP mapping, and contacting your Internet Service Provider (ISP) regarding such unauthorized use.</p>
        <h2>19. Links to Third Parties.</h2>
        <p>The Site may include links to other websites (each, a "Third Party Site"). We do not control or endorse any Third Party Site, and you agree that we are not responsible for the availability or contents of such Third Party Sites. Some of the products and services made available through the Site are provided in connection with third parties and subject to additional terms posted here which you are bound by in accordance with its terms, which terms are incorporated herein by reference.</p>
        <h2>20. Export Compliance.</h2>
        <p>By  viewing the website, downloading software or using embedded software in Hardware, you agree that you are solely responsible for complying with all United States export control regulations, including the Export Administration Regulations ("EAR"), and sanctions programs, including those administered by the United States Treasury Department's Office of Foreign Assets Controls ("OFAC"), and all other applicable international trade regulations. You agree that you will not download or use the Software without all required approvals in any proscribed destination (including Cuba, Iran, North Korea, Sudan, and Syria), on behalf of any proscribed entity or person, for any proscribed end use, or in any other manner contrary to these export regulations and sanctions programs. By downloading or using the Software, you represent, warrant and certify that you are not a proscribed end-user or utilizing this software for a proscribed end use under these regulations. This assurance shall survive the expiration or termination of this Agreement.</p>
        <h2>21. Suggestions and Improvements.</h2>
        <p>By sending us any ideas, suggestions, documents or proposals ("Feedback"), you agree that (i) your Feedback does not contain the confidential or proprietary information of third parties, (ii) we are under no obligation of confidentiality, express or implied, with respect to the Feedback, (iii) we may have something similar to the Feedback already under consideration or in development, and (iv) you grant us an irrevocable, non-exclusive, royalty-free, perpetual, worldwide right and license to use, modify, publish, distribute, create derivative works of and sublicense the Feedback in our sole discretion.</p>
        <h2>22. Termination.</h2>
        <p>a. We may terminate or suspend your account or ability to use the Site, in whole or in part, at our sole discretion, for any or no reason, and without notice or liability of any kind. For example, we may terminate or suspend your account or ability to use the Site if you misuse the Site. Any such termination or suspension could prevent you from accessing your account, the Site, Your Content, Site Content, or any other related information.</p>
        <p>b. You may terminate these Terms at any time by closing your account, discontinuing your use of any and all parts of the Site and if you have installed our Software, by uninstalling it. If you close your account, we may continue to use Your Content for our business purposes.</p>
        <p>c. In the event of any termination, whether by you or us, Sections 1, 8, 9, 21 – 29 of these Terms will continue in full force and effect.</p>
        <h2>23. Ownership.</h2>
        <p>We own Our Content, including but not limited to visual interfaces, interactive features, graphics, design, compilation, computer code, products, software, aggregate user review ratings, and all other elements and components of the Site excluding Your Content and Third Party Content. We also own the copyrights, trademarks, service marks, trade names, and other intellectual and proprietary rights throughout the world (the "IP Rights") associated with Our Content, the Software and the Site, which are protected by copyright, trade dress, patent, trademark laws and all other applicable intellectual and proprietary rights and laws. As such, you may not modify, reproduce, distribute, create derivative works or adaptations of, publicly display or in any way exploit any of Our Content or Software in whole or in part except as expressly authorized by us. Except as expressly and unambiguously provided herein, we do not grant you any express or implied rights, and all rights in and to the Site, the Software and Our Content are retained by us.</p>
        <h2>24. Warranties, Disclaimers, and Limitations of Liability.</h2>
        <p>a. THE SOFTWARE, SITE AND ALL SITE CONTENT IS MADE AVAILABLE TO YOU ON AN "AS IS" BASIS. WE (FOR THE PURPOSES OF SECTION 24 AND 25, WE AND OUR AFFILIATES, WIRELESS CARRIER AND OTHER SERVICE PROVIDERS, DISTRIBUTORS, ORIGINAL EQUIPMENT MANUFACTURERS, SUPPLIERS AND PARTNERS ARE COLLECTIVELY REFERRED TO AS "OUR," "WE" OR "US") MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, TO THE EXTENT PERMITTED BY APPLICABLE LAW, REGARDING ANY IMPLIED WARRANTY OF NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE CONCERNING (1) THE OPERATION AND FUNCTIONALITY OF THE SOFTWARE OR SITE, (2) THE ACCURACY, INTEGRITY, COMPLETENESS, QUALITY, LEGALITY, USEFULNESS, SAFETY, AND IP RIGHTS OF ANY OF THE SOFTWARE, SITE CONTENT, OR DATA TRANSMITTED THROUGH THE SITE, AND (3) THE PRODUCTS AND SERVICES ASSOCIATED WITH THE SOFTWARE, SITE OR SITE CONTENT.WE CAN'T PROMISE UNINTERRUPTED OR ERROR–FREE SERVICE, THAT DEFECTS WILL BE CORRECTED OR THAT THE SITE IS FREE FROM VIRUSES OR OTHER HARMFUL OR MALICIOUS COMPONENTS AND WE DON'T AUTHORIZE ANYONE TO MAKE ANY WARRANTIES ON OUR BEHALF. THIS DOESN'T DEPRIVE YOU OF ANY WARRANTY RIGHTS YOU MAY HAVE AGAINST ANYONE ELSE. WE MAKE NO REPRESENTATIONS OR WARRANTIES ON THE ACCURACY, COMPLETENESS OR TIMELINESS OF ANY LOCATION OR OTHER DATA MADE AVAILABLE TO YOU. YOUR USE OF ANY INFORMATION AVAILABLE THROUGH THE PRODUCTS,  SOFTWARE AND/OR SERVICES IS AT YOUR OWN RISK AND RESPONSIBILITY.</p>
        <p>b. UNLESS THE LAW FORBIDS IT IN ANY PARTICULAR CASE, THE LIMITATIONS AND WAIVERS IN THIS SECTION WILL APPLY REGARDLESS OF THE THEORY OF LIABILITY, WHETHER STATUTORY, FRAUD, MISREPRESENTATION, BREACH OF CONTRACT, PERSONAL INJURY, PRODUCTS LIABILITY OR ANY OTHER THEORY.  YOU WILL NOT BE ENTITLED TO SEEK ANY ATTORNEYS FEES, INDIRECT, SPECIAL, TREBLE, CONSEQUENTIAL OR PUNITIVE DAMAGES FROM US. YOU AGREE THAT WE ARE NOT LIABLE FOR PROBLEMS CAUSED BY YOU OR A THIRD PARTY; BY WIRELESS CARRIERS, DATA CENTERS, BUILDINGS, ACCIDENTS, HILLS, NETWORK CONGESTION, TUNNELS, TOWERS, WEATHER OR OTHER THINGS WE DON'T CONTROL; OR BY ANY ACT OF GOD.  YOU ACKNOWLEDGE AND AGREE THAT YOU HAVE NO CONTRACTUAL RELATIONSHIP WHATSOEVER WITH ANY OF OUR SERVICE PROVIDERS AND YOU ARE NOT A THIRD PARTY BENEFICIARY OF ANY AGREEMENT BETWEEN US AND SUCH SERVICE PROVIDERS. UNLESS YOU HAVE A SEPARATE CONTRACT WITH OUR SERVICE PROVIDERS, SUCH SERVICE PROVIDERS HAVE NO LEGAL, EQUITABLE OR OTHER LIABILITY OF ANY KIND TO YOU AND YOU WAIVE ANY AND ALL CLAIMS OR DEMANDS FOR SUCH LIABILITY. OUR MAXIMUM LIABILITY TO YOU UNDER ANY THEORY (INCLUDING BUT NOT LIMITED TO FRAUD, MISREPRESENTATION, BREACH OF CONTRACT, PERSONAL INJURY, OR PRODUCTS LIABILITY) IS LIMITED TO US $100.</p>
        <h2>25. Indemnity.</h2>
        <p>You agree to indemnify and hold us, our parents, subsidiaries, affiliates, any related companies, suppliers, licensors and partners, and the officers, directors, employees, agents and representatives of each of them harmless, including costs, liabilities and legal fees, from any claim or demand made by any third party due to or arising out of (i) your access to or use of the Site, (ii) your violation of these Terms, (iii) claims for libel, slander or any property damage, personal injury or death, (iv) the use, failure to use, or inability to use the Site or Software or any products or services available through the Site, caused directly or indirectly by you, or (v) the infringement by you, or any third party using your account, of any intellectual property or other right of any person or entity. We reserve the right, at your expense, to assume the exclusive defense and control of any matter for which you are required to indemnify us and you agree to cooperate with our defense of these claims. You agree not to settle any matter without our prior written consent. We will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>
        <h2>26.  Disputes and Mandatory Arbitration Clause.</h2>
        <p>IT IS IMPORTANT THAT YOU READ THIS ARBITRATION CLAUSE.  IT PROVIDES THAT YOU MAY BE REQUIRED TO SETTLE ANY CLAIM OR DISPUTE THROUGH ARBITRATION, EVEN IF YOU WOULD PREFER TO LITIGATE SUCH CLAIMS BEFORE A JURY.  OTHER RIGHTS THAT YOU WOULD HAVE IF YOU WENT TO COURT, SUCH AS DISCOVERY OR THE RIGHT TO APPEAL THE DECISION, MAY NOT BE AVAILABLE IN ARBITRATION OR MAY BE MORE LIMITED.   </p>
        <p>a.  The Federal Arbitration Act applies these Terms.  Any dispute, controversy or claim between us, regardless of whether based on your subscription, the services, the balance on your account, your Product, any prior account you had with us, your application, these Terms, any prior agreement or any other facts, and regardless of whether the legal theory is based on these Terms, another common law theory, a statute or another ground (each, a “Claim”), will be settled by neutral arbitration before the American Arbitration Association (“AAA”).  Claims within the applicable small claims limit in your jurisdiction may be brought in small claims court rather than arbitration. </p>
        <p>b.  Forum Selection and Applicable Procedure.  Unless you and we agree otherwise, the arbitration will take place in Salt Lake County, Utah.  For Claims over $10,000 the AAA's Wireless Industry Arbitration ("WIA") rules will apply.  In large/complex cases under the WIA rules, the arbitrators must apply the Federal Rules of Evidence and a party may have the award reviewed by a panel of three new arbitrators.  For Claims of $10,000 or less, the complaining party can choose either the AAA's Supplementary Procedures for Consumer-Related Disputes or individual action in small claims court filed in Salt Lake County, UT.  You can obtain procedures, rules and fee information from the AAA (www.ADR.org).  Each of us may be required to exchange relevant evidence in advance.  For claims of $10,000 or less, we agree that you may choose whether the arbitration will be conducted solely on the basis of documents submitted to the arbitrator, by telephonic hearing, or by an in-person hearing. To initiate arbitration under these Terms, contact the AAA, which will provide the necessary forms for you to submit.  In the case of a conflict between any arbitration rules and these Terms, these Terms govern.</p>
        <p>c.  Intentionally Omitted. </p>
        <p>d.  CLASS ACTION WAIVER.  YOU AND WE EACH WAIVE THE RIGHT TO BRING CLAIMS ON A REPRESENTATIVE OR CLASS BASIS, EVEN IF AAA OR WIA PROCEDURES OR RULES WOULD ALLOW IT.  WE ARE EACH WAIVING THE RIGHT TO A JURY OR COURT TRIAL.  The arbitrator may award monetary or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party’s individual Claim.  IF THIS CLASS ACTION WAIVER IS DEEMED UNENFORCEABLE, THEN THE ENTIRE ARBITRATION PROVISION SHALL BE DEEMED UNENFORCEABLE.  IN NO CIRCUMSTANCE SHALL CLASS CLAIMS BE BROUGHT OR ADJUDICATED IN ARBITRATION.</p>
        <p>e. Claim Notices.  If you or we have a Claim against the other, before initiating, joining, or participating in any lawsuit, arbitration or other legal proceeding, the complaining party shall give the other party: (1) a written notice of the Claim (referred to below as a “Claim Notice”), explaining in reasonable detail the nature of the Claim and any supporting facts; and (2) a reasonable good faith opportunity (not less than 30 days) to resolve the claim without the necessity of a legal proceeding.  Any Claim Notice directed to Sensor Cert shall be sent to us at Sensor Cert LLC, Attn: Legal Department, 450 S SIMMONS WAY STE 670 Kaysville, UT 84037.  Any Claim Notice directed to you shall be sent to your address appearing in our records or, if you advise us that you are represented by counsel, to your attorney at your attorney’s office.  If you or we fail to comply with this Claim Notices provision before commencing a lawsuit, arbitration or other legal proceeding, that failure shall be a complete defense to all claims asserted in such proceeding.</p>
        <p>f.  Use of Arbitration Award or Judgments in Subsequent Cases.   An arbitration award and any judgment confirming it only applies to the arbitration in which it was awarded and can’t be used in any other case except to enforce the award itself.</p>
        <p>g. Cure Provision.  You and we intend for both of us to have the right to arbitrate disputes on an individual basis as set forth above.  If a court finds any reason to invalidate or refuse to enforce this arbitration provision, the party aggrieved by that decision shall have the right to take unilateral action to eliminate the basis for the court’s decision, such as by waiving any right or remedy it has under these Terms or agreeing to additional fee or cost shifting.  This cure right may be exercised during briefing of a motion to compel arbitration, during oral argument, or in a renewed motion to compel arbitration.  If a renewed motion is filed, you and we agree that the exercise of cure rights hereunder shall constitute new facts permitting such a renewed motion.</p>
        <p>h. Applicable Law. Except to the extent we've agreed otherwise in the provisions on arbitration, or as required by Federal law, these Terms and all disputes between us (whether or not based on these Terms) are governed by the laws of the state of Utah, without regard to that state’s conflict of laws principles.</p>
        <h2>27. Miscellaneous.</h2>
        <p>a. U.S. Government Restricted Rights. The Software and Site are provided with Restricted Rights. Federal, state and local governments agree to the terms and conditions of this commercial license.</p>
        <p>b. No agency, partnership, joint venture, or employment is created as a result of these Terms, and you do not have any authority of any kind to bind us in any respect whatsoever.</p>
        <p>c. We may provide you with notices, including those regarding changes to these Terms by email, regular mail or postings on the Site. You hereby waive service of process in connection with any legal matters or proceedings pertaining to these Terms, and agree that (to the extent permitted by applicable law) service at the address indicated in your account information is proper service.  Such service may be served by mail or fax, which shall be deemed full and complete service on you.  If you intend to carry out legal action of any kind against the Site you are required to contact us at least ten (10) business days before any legal claim is made.</p>
        <p>d. These Terms contain the entire agreement between you and us regarding the use of the Site, and supersede any prior agreement between you and us on such subject matter. The parties acknowledge that no reliance is placed on any representation made but not expressly contained in these Terms.</p>
        <p>e. Any failure on our part to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder.</p>
        <p>f. If any provision of these Terms is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that these Terms shall otherwise remain in full force and effect and enforceable.</p>
        <p>g. These Terms are not assignable, transferable or sublicensable by you except with our prior written consent, but may be assigned or transferred by us without restriction. Any assignment attempted to be made in violation of these Terms shall be void.</p>
        <p>h. The section titles in these Terms are for convenience only and have no legal or contractual effect.</p>
        <h2>28. Trademarks</h2>
        <p>Sensor Cert is a trademark of Sensor Cert, LLC.  All other marks are owned by their respective owners.</p>
        <h2>29. Contact and Violations.</h2>
        <p>Please contact us with any questions regarding these Terms. Please report any violations of these Terms to us using the Feedback form within the Website or write to us at:</p>
        <p>
            Sensor Cert LLC<br />
            Attention: Legal Department<br />
            9909 West Fairview Ave.<br />
            Littleton, CO 80127
        </p>
        <h2>Effective Date: May 25, 2018</h2>
        <p></p>
        <p>- See more at: <a href="http://www.sensorcert.com/terms.html" target="_blank">http://www.sensorcert.com/terms.html</a></p>
    </div>