<%@ Control Language="C#" Inherits="System.Web.Mvc.ViewUserControl<Monnit.Sensor>" %>


<div class="row">
    <div class="word-choice">
      <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Max & Avg - X-Delta","X-Delta Value (g)")%>
    </div>
     <div class="word-def">
       <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Max & Avg - X-Delta","Acceptable range of X g-force values to deviate before triggering again.")%>
        <hr />
    </div>
</div>

<div class="row">
    <div class="word-choice">
      <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Max & Avg - Y-Delta","Y-Delta Value (g)")%>
    </div>
     <div class="word-def">
       <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Max & Avg - Y-Delta","Acceptable range of Y g-force values to deviate before triggering again.")%>
        <hr />
    </div>
</div>

<div class="row">
    <div class="word-choice">
      <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Max & Avg - Z-Delta","Z-Delta Value (g)")%>
    </div>
     <div class="word-def">
       <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Max & Avg - Z-Delta","Acceptable range of Z g-force values to deviate before triggering again.")%>
        <hr />
    </div>
</div>

<div class="row">
    <div class="word-choice">
      <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Magnitude Delta Value (g)","Magnitude Delta Value (g)")%>
    </div>
     <div class="word-def">
       <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Max & Avg - Magnitude Delta Value","Acceptable range of Magnitude values to deviate before triggering again.")%>
        <hr />
    </div>
</div>

<div class="row">
    <div class="word-choice">
      <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Output Data Rate","Output Data Rate")%>
    </div>
     <div class="word-def">
       <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Max & Avg - Output Data Rate","Measurement Frequency of the accelerometer")%>
        <hr />
    </div>
</div>

<div class="row">
    <div class="word-choice">
      <%: Html.TranslateTag("Accelerometer Mode","Accelerometer Mode")%>
    </div>
     <div class="word-def">
      <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Max & Avg - Accelerometer Mode", "Select the range (2g, 4g, 8g) and the type of readings generated by the accelerometer. Normal includes orientation (gravity) and vibration forces. High Pass Filter includes only vibration forces or rapidly changing forces.")%> 
        <hr />
    </div>
</div>

<div class="row">
    <div class="word-choice">
      <%: Html.TranslateTag("Re-Arm Time (seconds)","Re-Arm Time (seconds)")%>
    </div>
     <div class="word-def">
      <%: Html.TranslateTag("Sensor/ApplicationCustomization/Help|Max & Avg - Re-Arm time", "The time in seconds after a triggering event that the sensor will wait before being able to produce another triggering event.")%> 
        <hr />
    </div>
</div>